#!/bin/bash
set -ex

apt update -y
apt install -y less htop coreutils jq dnsutils iotop bpfcc-tools tree openjdk-11-jdk-headless
apt install -y --no-install-recommends collectd

cat >/etc/collectd/collectd.conf.d/network.conf <<EOF
LoadPlugin contextswitch
LoadPlugin cpu
LoadPlugin disk
LoadPlugin irq
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin processes
LoadPlugin rrdtool
LoadPlugin vmem

<Plugin processes>
    <Process java>
        CollectContextSwitch true
        CollectFileDescriptor true
        CollectMemoryMaps true
    </Process>
</Plugin>

<Plugin network>
	Server "collectd-server.c.developer-222401.internal" "25826"
</Plugin>
EOF
systemctl restart collectd

mkdir -p /tmp/debs
wget -N -P /tmp/debs https://build.rchain-dev.tk/release/v0.9.17/rnode_0.9.17_all.deb
apt install -y /tmp/debs/*.deb

systemctl stop rnode || true
umount /var/lib/rnode || true

echo "2048 - L" | sfdisk -W always /dev/disk/by-id/google-local-nvme-ssd-0
partprobe
sleep 1
mkfs.ext4 -F /dev/disk/by-id/google-local-nvme-ssd-0-part1
mount /dev/disk/by-id/google-local-nvme-ssd-0-part1 /var/lib/rnode
chown rnode. /var/lib/rnode

cat >/var/lib/rnode/rnode.conf <<EOF
rnode {
	server {
		upnp = false
		standalone = true
	}
	casper {
		validator-private-key = "5244db4ed932767f78da3931fcfe610cc40e85b2cc8b66606d47767e504c2730"
		validator-public-key = "0452230abaa5e6630067008686c7b26548f453fb6055d2e67bd3793525e1e8aed32ee7491c2dfecfd2055352dbf3a539b231ba1cb0cc47d5dbcfa6de70a5325a57"
	}
}
EOF

mkdir /var/lib/rnode/genesis

cat >/var/lib/rnode/genesis/bonds.txt <<EOF
0452230abaa5e6630067008686c7b26548f453fb6055d2e67bd3793525e1e8aed32ee7491c2dfecfd2055352dbf3a539b231ba1cb0cc47d5dbcfa6de70a5325a57 10000000000
EOF

# Deployer:
# private key	d18ca8770fc5dc2a6001329751eef57038b4ac18a77582ebe5c1f531d1966ea4
# public key	0465a410d33815a6d0a65bd42f359d7c5ad968b8385c949adb3874207144b3183ebcf9fb6cfbfeb76a3f803fec9cf67f7ef6f3852f97c14b762a3dd1c8827ed996
# rev address	11112mzEQdaEaQECbRT8S3zr6NKyvXNGWafJi8dPHnXfjGpWaunKL1
# eth address	c6ae40fe10f3e5b60a1480f49464b25006b63ae2

cat >/var/lib/rnode/genesis/wallets.txt <<EOF
c6ae40fe10f3e5b60a1480f49464b25006b63ae2,1000000000,0
EOF

systemctl start rnode

wget -N -P /tmp https://gist.githubusercontent.com/nzpr/3fc582b55089bcee344d4f51bbf181e6/raw/d1f8a308933d42a5c79f17dd185bd51e4221b4d2/cpu-test.rho

while ! grep -q 'Making a transition to Running' /var/lib/rnode/rnode.log; do
	sleep 1
done

rnode deploy --phlo-limit 1000000000 --phlo-price 1 --private-key d18ca8770fc5dc2a6001329751eef57038b4ac18a77582ebe5c1f531d1966ea4 /tmp/cpu-test.rho
rnode propose
